create project cinema vladimir henriquez
UnirCs/DWFS-PER9208-2324 pull request #11
Opened 2024-03-25 18:56 UTC by wladydj

Creación del proyecto de html y css "cinema" del estudiante Vladimir Henriquez

2024-03-26 08:50 UTC, UnirCs commented on debug.log
Este archivo no se puede incluir en la PR

2024-03-26 08:51 UTC, UnirCs requested changes
El ejercicio está bien, pero hay que eliminar el fichero que está fuera de tu carpeta

2024-03-28 04:49 UTC, wladydj commented
Se realizó corrección y se creó el proyecto CV, estudiante Vladimir henriquez

2024-03-28 15:01 UTC, UnirCs approved these changes
OK!

2024-03-28 15:01 UTC, merged