Temas 2, 3, 4 Javier Castañeda
UnirCs/DWFS-PER9208-2324 pull request #124
Opened 2024-04-29 21:58 UTC by javier12casta

2024-04-29 23:18 UTC, UnirCs commented on .gitignore
Debes revertir este cambio en mi archivo

2024-04-29 23:18 UTC, UnirCs commented on Tema_2/Javier_Alejandro_Castaneda_Celis/cinema/cinema.js
> +                    break;
break

2024-04-29 23:18 UTC, UnirCs commented on Tema_2/Javier_Alejandro_Castaneda_Celis/cinema/cinema.js
> +            break;
break

2024-04-29 23:19 UTC, UnirCs requested changes
Revierte cambios en mi archivo.

Por otro lado, como he comentado varias veces, está prohibido usar breaks/continues/return dentro de bucles. Violan las invariantes y no demuestran control de la lógica que se está implementando.
Los bucles deben terminar de forma lógica y no forzados.

2024-04-30 14:09 UTC, javier12casta commented on .gitignore
Se remueve cambio en el archivo

2024-04-30 14:10 UTC, javier12casta commented on Tema_2/Javier_Alejandro_Castaneda_Celis/cinema/cinema.js
> +                    break;
Se ajusta código para remover uso de break

2024-04-30 14:10 UTC, javier12casta commented on Tema_2/Javier_Alejandro_Castaneda_Celis/cinema/cinema.js
> +            break;
Se ajusta código para remover uso de break

2024-04-30 14:11 UTC, javier12casta commented
Buen día

Se resuelve los problemas mencionados, de igual manera agradecer la observación

2024-04-30 18:03 UTC, closed without merging