Tema 6 - Juan Maximiliano Aguilar Abanto
UnirCs/DWFS-PER9208-2324 pull request #134
Opened 2024-05-11 22:23 UTC by aguil17

2024-05-17 10:20 UTC, UnirCs commented on Tema_6/Juan_Maximiliano_Aguilar_Abanto/API_Calculadora.md
add, multiply, divide... son todo verbos.
Recuerda que deben ser sustantivos, y en plural. Al igual que lo tienes en los otros ejercicios, este no es distinto, simplemente hay que pensar qué sustantivo utilizar (usa español o inglés, da igual)

por otro lado... que es calculators?? calculadoras?? es una api de calculadoras, o una api de 1 calculadora con operaciones. Piensa si quieres tener tener 1 recurso operacion con un endpoint post para crearlas y que el body pueda cambiar con cada tipo de operacion 1 un endpoint get para obtener el detalle deuna operacion, o N recursos (sumas, restas, multiplicaciones...) con 2 endpoints para cada uno, uno para crear y otro para listar. Pero debe haber coherencia.

Si tengo "/api/sumas" para POST, tengo "api/sumas/1" para GET. No puede haber cambios a nivel Uri cuando los metodos sean distintos.

2024-05-17 10:20 UTC, UnirCs commented on Tema_6/Juan_Maximiliano_Aguilar_Abanto/Hunde_La_Flota.md
> +| GET        | /api/v1/game/{gameId}                | N/A           | N/A                    | `{"jugadores": [1,2,3],"ganador":3, "barcos": [ { "jugador": 1,"barcos": [1,2,3 ]},{"jugador": 2,"barcos
games, plural

2024-05-17 10:21 UTC, UnirCs commented on Tema_6/Juan_Maximiliano_Aguilar_Abanto/Hunde_La_Flota.md
> +| GET        | /api/v1/players/{playerId}/ships                | N/A           | N/A                    | `{"barcos": [1,2,3]}`                                    | 200 OK<br/>404 Not Found<br/>500 I
si los barcos se obtienen ligados a un jugador, ¿por qué se eliminan y se crean sin estar asociados a un jugador? No es coherente este endpoint con los demas

2024-05-17 10:22 UTC, UnirCs commented on Tema_6/Juan_Maximiliano_Aguilar_Abanto/Hunde_La_Flota.md
> +| POST        | /api/v1/shots                | N/A           | `{"coordenadas": "A1", "resultado": "tocado","jugadorAtacante": 1, "jugadorVictima" : 2, "hora": "10:10:20"}`                    | `{"id
Pregúntate si tiene sentido que un disparo no esté asociado, al menos, a una partida

2024-05-17 10:23 UTC, UnirCs commented on Tema_6/Juan_Maximiliano_Aguilar_Abanto/Reserva_Butacas_Cine.md
OK!

2024-05-17 10:23 UTC, UnirCs requested changes
El del cine bien. Respecto a los otros dos revisa lo que te indico.
Buen trabajo en cualquier caso.

2024-05-23 17:21 UTC, aguil17 commented on Tema_6/Juan_Maximiliano_Aguilar_Abanto/API_Calculadora.md
@UnirCs 
Esto fue corregido

2024-05-23 17:21 UTC, aguil17 commented on Tema_6/Juan_Maximiliano_Aguilar_Abanto/Hunde_La_Flota.md
> +| GET        | /api/v1/game/{gameId}                | N/A           | N/A                    | `{"jugadores": [1,2,3],"ganador":3, "barcos": [ { "jugador": 1,"barcos": [1,2,3 ]},{"jugador": 2,"barcos
@UnirCs 
Esto fue corregido

2024-05-23 17:21 UTC, aguil17 commented on Tema_6/Juan_Maximiliano_Aguilar_Abanto/Hunde_La_Flota.md
> +| GET        | /api/v1/players/{playerId}/ships                | N/A           | N/A                    | `{"barcos": [1,2,3]}`                                    | 200 OK<br/>404 Not Found<br/>500 I
@UnirCs 
Esto fue corregido

2024-05-23 17:21 UTC, aguil17 commented on Tema_6/Juan_Maximiliano_Aguilar_Abanto/Hunde_La_Flota.md
> +| POST        | /api/v1/shots                | N/A           | `{"coordenadas": "A1", "resultado": "tocado","jugadorAtacante": 1, "jugadorVictima" : 2, "hora": "10:10:20"}`                    | `{"id
@UnirCs 
Esto fue corregido

2024-05-23 17:22 UTC, aguil17 commented
@UnirCs 
las observaciones fueron corregidas

2024-05-24 09:16 UTC, UnirCs approved these changes
OK!

2024-05-24 09:16 UTC, merged