Añade ejercicios tema 6
UnirCs/DWFS-PER9208-2324 pull request #144
Opened 2024-05-17 12:59 UTC by gondite

2024-05-18 20:47 UTC, UnirCs commented on Tema_6/Ignacio_Gonzalez_Diaz-Tendero/Calculadora.md
sum, subctract, divide... son todo verbos.
Recuerda que deben ser sustantivos, y en plural. Al igual que lo tienes en los otros ejercicios, este no es distinto, simplemente hay que pensar qué sustantivo utilizar (usa español o inglés, da igual)

Piensa si quieres tener tener 1 recurso operacion con un endpoint post para crearlas y que el body pueda cambiar con cada tipo de operacion 1 un endpoint get para obtener el detalle deuna operacion, o N recursos (sumas, restas, multiplicaciones...) con 2 endpoints para cada uno, uno para crear y otro para listar. Pero debe haber coherencia.

Si tengo "/api/sumas" para POST, tengo "api/sumas/1" para GET. No puede haber cambios a nivel Uri cuando los metodos sean distintos.

2024-05-18 20:48 UTC, UnirCs commented on Tema_6/Ignacio_Gonzalez_Diaz-Tendero/Hundir_flota.md
> +|POST        | /games/{game_id}/start                    | N/A                                                              | {"message": "Game started"}
usas un verbo y una operacion de creacion para modificar el estado de un recurso. esto es PATCH sobre un recurso game ya creado

2024-05-18 20:48 UTC, UnirCs commented on Tema_6/Ignacio_Gonzalez_Diaz-Tendero/Hundir_flota.md
> +|POST        | /games/{game_id}/finish                   | N/A                                                              | {"message": "Game finished", "winner_id": 123}
usas un verbo y una operacion de creacion para modificar el estado de un recurso. esto es PATCH sobre un recurso game ya creado

2024-05-18 20:49 UTC, UnirCs commented on Tema_6/Ignacio_Gonzalez_Diaz-Tendero/Reserva_butacas.md
> +| POST        | /bookings/{bookingId}/payment | -            | {"amount": 20}                                                                 | {"bookingId": 101, "userId": 789, "roomId": 456, "seats
Siempre en plural, "payments"

2024-05-18 20:49 UTC, UnirCs requested changes
No está mal, revisa lo que te he comentado. Buen trabajo

2024-05-22 23:18 UTC, gondite commented
Corrección de errores

2024-05-23 06:03 UTC, UnirCs commented on Tema_6/Ignacio_Gonzalez_Diaz-Tendero/Hundir_flota.md
> +| GET         | /games/{game_id}/ships/{player_id} | N/A                                                                                            | {"ships": [{"ship_id": 101, "player_id": 123, "sh
seria ship_id simplemente tenlo en cuenta para cambiarlo

2024-05-23 06:04 UTC, UnirCs approved these changes
OK!

2024-05-23 06:04 UTC, merged