Merge from Freddy Barragán
UnirCs/DWFS-PER9208-2324 pull request #18
Opened 2024-03-29 15:44 UTC by Fretex26

Cinema and CV activities created

2024-03-30 14:58 UTC, UnirCs commented on Tema_1/Freddy_Barragan/CV/cv.html
> +                            <div class="progress-bar" style="width: 100%"></div>
estilo inline

2024-03-30 14:58 UTC, UnirCs commented on Tema_1/Freddy_Barragan/CV/cv.html
> +                            <div class="progress-bar" style="width: 75%"></div>
estilo inline..

2024-03-30 14:58 UTC, UnirCs requested changes
Debes eliminar los estilos inline al no ser una buena práctica, tal como comenté en clase

2024-04-02 01:56 UTC, Fretex26 commented on Tema_1/Freddy_Barragan/CV/cv.html
> +                            <div class="progress-bar" style="width: 100%"></div>
Hola Profe, ¿Se refiere a que no use la progressbar despues de la palabra "Español"? o ¿a que no use una tabla para acomodar la palabra "Español" y luego la progressbar? o ¿a que no use dos div seguidos?

2024-04-02 02:05 UTC, Fretex26 commented
Inline Styles eliminados

2024-04-02 07:42 UTC, UnirCs approved these changes
OK!

2024-04-02 07:42 UTC, merged