Añade ejercicios Tema 2
UnirCs/DWFS-PER9208-2324 pull request #40
Opened 2024-04-07 17:55 UTC by gondite

2024-04-08 08:25 UTC, UnirCs commented on Tema_2/Ignacio_Gonzalez_Diaz-Tendero/Cinema/cinema.js
> +                    return selectedSeats; // Devolvemos los asientos seleccionados
termina de forma lógica los bucles, no mediante breaks, continues o returns

2024-04-08 08:26 UTC, UnirCs requested changes
Los ejercicios bien, a excepción del t2 de cine. No violes invariantes de bucles forzando la finalización tú, deja que el programa de forma lógica actúe.

2024-04-09 11:31 UTC, gondite commented
Corrección de bucle realizada. Gracias!

2024-04-12 10:51 UTC, UnirCs approved these changes

2024-04-12 10:51 UTC, merged