Tarea 2
UnirCs/DWFS-PER9208-2324 pull request #41
Opened 2024-04-07 21:33 UTC by aguil17

2024-04-08 08:27 UTC, UnirCs commented on Tema_2/Juan_Aguilar_Abanto/cinema/cinema.js
> +                return asientoSugeridos;
no finalices con breaks, returns o continues dentro de bucles, termina siempre los bucles de forma lógica.

2024-04-08 08:28 UTC, UnirCs requested changes
Bien el de los filtros, pero en el del cine revisa lo que comenté en clase; no terminar bucles nunca con sentencias de salto como breaks, returns o continues ya que violan las invariantes de los bucles y dificultan la lectura y la mantenibilidad del código.

2024-04-09 01:28 UTC, aguil17 commented on Tema_2/Juan_Aguilar_Abanto/cinema/cinema.js
> +                return asientoSugeridos;
Esto fue corregido.

2024-04-09 01:28 UTC, aguil17 commented
La observacion fue corregida

2024-04-12 10:52 UTC, UnirCs approved these changes
OK!

2024-04-12 10:52 UTC, merged