Desarrollo ejercicios Tema 1, Ej1: CV y Ej2:Cinema
UnirCs/DWFS-PER9208-2324 pull request #46
Opened 2024-04-08 05:47 UTC by DiegoRueda369

2024-04-08 08:32 UTC, UnirCs commented on Tema_1/Diego_Rueda/ej1_cv/index.html
> +                            <p style="font-weight: bold">Actividades:</p>
Estilos inline

2024-04-08 08:32 UTC, UnirCs commented on Tema_1/Diego_Rueda/ej1_cv/index.html
> +                            <p style="font-weight: bold">Actividades:</p>
Estilos inline

2024-04-08 08:33 UTC, UnirCs requested changes
Corrige los estilos inline innecesarios en el primer ejercicio Diego, por lo demás todo OK.

2024-04-11 03:19 UTC, DiegoRueda369 commented
en css cree un estilo llamado "#subtitulo{}" y otro estilo llamado ".li_subtitulo{}" en el html en la etiqueta "< li >" use ambos y dan igual resultado "< li class="li_subtitulo" >" tambien use "< li id="subtitulo" >". Cuál sería la diferencia? y cuál sería el más recomendable usar?

2024-04-12 10:54 UTC, UnirCs approved these changes

2024-04-12 10:55 UTC, UnirCs commented
En un caso estás usando el atributo id con # y en otro el atributo class con .
Si solo quieres aplicar un estilo a un unico elemento, la opcion de ID es la correcta. Si quieres aplicar el estilo a varios elementos que comparten la misma clase, la opcion correcta es la segunda.

Lo que NO seria correcto es que aplicases el mismo ID a varios <li> ya que para eso se utiliza la clase. Usariamos el id solo si queremos aplicar el estilo concretamente  a 1 elemento por alguna razon en concreto

2024-04-12 10:56 UTC, merged