Practica 1
UnirCs/DWFS-PER9208-2324 pull request #69
Opened 2024-04-14 20:39 UTC by Efraindiaz10

2024-04-16 21:34 UTC, UnirCs commented on Tema_1/Efrain_Diaz/cinema/index.html
> +                <div class="d-grid gap-3" style="grid-template-columns: 1fr;">
Estilos inline

2024-04-16 21:35 UTC, UnirCs requested changes
Los ejercicios están bien, pero quita ese estilo inline por favor

2024-04-21 11:23 UTC, Efraindiaz10 commented
Estilos modificados

2024-04-21 22:14 UTC, UnirCs commented
Sigue habiendo estilos inline

2024-04-25 11:19 UTC, UnirCs commented on .gitignore
Este archivo es global y no se puede modificar

2024-04-25 11:19 UTC, UnirCs requested changes
Revierte por favor cambios en el archivo que no es tuyo

2024-04-25 16:28 UTC, closed without merging