Tema_1 CV y Cinema
UnirCs/DWFS-PER9208-2324 pull request #71
Opened 2024-04-14 22:40 UTC by JohnRoaUnir

Tema 1 Cv y Cinema HTML y CSS

2024-04-16 21:37 UTC, UnirCs commented on Tema_1/John_Jairo_Roa_Castaneda/CV/Index.html
> +            <h2 style="text-align: center;">Ingeniero de Desarrollo</h2>
estilos inline

2024-04-16 21:37 UTC, UnirCs requested changes
Los ejercicios están bien pero elimina los estilos inline que tienes

2024-04-22 04:39 UTC, JohnRoaUnir commented
se suben cambios en este meregerequest

2024-04-22 06:41 UTC, UnirCs approved these changes
OK!

2024-04-22 06:41 UTC, merged

2024-04-29 05:40 UTC, JohnRoaUnir commented on Tema_1/John_Jairo_Roa_Castaneda/CV/Index.html
> +            <h2 style="text-align: center;">Ingeniero de Desarrollo</h2>
Buenas noches profesor, ya fue resuelto y enviado para su aprobación en el pullrequest de la semana pasada