Tema 01 Fet (CV)(CINE) Vista de Curriculum y cine.
UnirCs/DWFS-PER9208-2324 pull request #72
Opened 2024-04-15 00:40 UTC by WilliamPMorocho

Tarea del Tema 01

2024-04-16 21:37 UTC, UnirCs commented on Tema_1/William_Patricio_Morocho/cv/index.html
> +                    <div class="progress" style="width: 50%;">
estilos inline

2024-04-16 21:37 UTC, UnirCs commented on Tema_1/William_Patricio_Morocho/cv/index.html
> +                    <div class="progress" style="width: 50%;">
estilos inline

2024-04-16 21:38 UTC, UnirCs requested changes
Los ejercicios estan bien pero elimina los estilos inline que tienes

2024-04-21 03:29 UTC, WilliamPMorocho commented
Se realizo la eliminacion de los estilos inline

2024-04-21 22:15 UTC, UnirCs requested changes
Sigue habiendo estilos inline

2024-04-25 11:21 UTC, UnirCs commented
PR próxima a ser cerrada por inactividad

2024-04-27 12:34 UTC, UnirCs commented
PR Cerrada por inactividad

2024-04-27 12:34 UTC, closed without merging