Tema 2 Filtros y Cinema
UnirCs/DWFS-PER9208-2324 pull request #75
Opened 2024-04-15 04:05 UTC by ChristianViracocha44

Desarrollo del Tema 2 Filtros y Cinema

2024-04-16 21:40 UTC, UnirCs commented on Tema_2/Christian_David_Viracocha_Suntaxi/Cinema/cinema.js
> +                return sugeridos;
finaliza el bucle de forma lógica y no forzada

2024-04-16 21:41 UTC, UnirCs requested changes
Finaliza el bucle de suggest de forma logica y no mediante breaks o returns dentro de bucles

2024-04-20 18:19 UTC, UnirCs commented
Sigue faltando la corrección que he sugerido

2024-04-21 01:20 UTC, ChristianViracocha44 commented
Ya realice el cambio solicitado y envié con los ejercicios del Tema 3

2024-04-21 01:26 UTC, ChristianViracocha44 commented on Tema_2/Christian_David_Viracocha_Suntaxi/Cinema/cinema.js
> +                return sugeridos;
Si ya realice el cambio solicitado, y no me di cuenta del comentario después que le envié los ejercicios del tema 3, lo siento

2024-04-21 22:15 UTC, UnirCs approved these changes
OK!

2024-04-21 22:16 UTC, merged