ejercicio cinema tema 2
UnirCs/DWFS-PER9208-2324 pull request #87
Opened 2024-04-16 13:36 UTC by xaqj

ejercicio cinema tema 2

2024-04-16 21:48 UTC, UnirCs commented on Tema_2/Xavier_Antonio_Quevedo_Jumbo/cinema/cinema.js
> +            return suggestedSeats;
intenta finalizar el bucle de forma logica

2024-04-16 21:49 UTC, UnirCs requested changes
Xavier, intenta finalizar el bucle de t2 de forma logica y no con un break o return. Si esto se te atasca, prueba a revisar implementaciones de otros compañeros o la que yo puse por el foro como ejemplo

2024-04-17 20:34 UTC, xaqj reviewed
ok, esta modificado

2024-04-20 18:20 UTC, UnirCs approved these changes
OK!

2024-04-20 18:21 UTC, merged