Practica 1: Diseños CV y Sala de Cine
UnirCs/DWFS-PER9208-2324 pull request #9
Opened 2024-03-25 00:55 UTC by neurip

2024-03-25 18:19 UTC, UnirCs commented on Tema_1/Neuri-R-Pena-Torres/CV/index.html
> +			<div style="padding: 16px;">
No es una buena práctica usar estilos inline, como comenté en clase.
Más info: https://www.thoughtco.com/avoid-inline-styles-for-css-3466846

2024-03-25 18:20 UTC, UnirCs requested changes
Los ejercicios están bien, pero elimina todos los estilos inline que hay

2024-03-25 23:14 UTC, neurip commented
cambios apicados

2024-03-26 08:49 UTC, UnirCs approved these changes
estupendo ahora!

2024-03-26 08:49 UTC, merged