Tareas José Toledo
UnirCs/DWFS-PER9208-2324 pull request #95
Opened 2024-04-18 10:23 UTC by JoseToledo046

Buenos días,
Envío tareas 02 03 04

2024-04-19 17:44 UTC, JoseToledo046 commented
Buenas tardes,
Agrego la tarea de filtros.
Tengo una duda, al guardar las imágenes estas se encuentran rotadas 90°

2024-04-20 18:17 UTC, UnirCs commented on Tema_2/Jose_Roberto_Toledo_Illescas/cinema/cinema.js
> +                    return temp;
.

2024-04-20 18:18 UTC, UnirCs requested changes
Como he ido comentando en clase, no se aceptan soluciones donde los finales de los bucles sean forzados y no lógicos, elimina los returns, breaks o continues dentro de bucles.

2024-04-25 11:20 UTC, UnirCs approved these changes
OK!

2024-04-25 11:20 UTC, merged